#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}

#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
#define VIAL_UNLOCK_TIMEOUT 2000
#define DYNAMIC_MACRO_COUNT 64
#define VIAL_DYNAMIC_KEYMAP_MACRO_COUNT 64
#define VIAL_EEPROM_LAYOUT_OPTIONS_SIZE 32768

/*


#define OS_DETECTION_DEBOUNCE 250
#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT
*/
